### ISSUE TITLE
CSS and JavaScript files not connected for 'Find My Number' game

### ISSUE THREAD

**Issue by rohan-raut** [deepakuniyaliit/hacktoberfest2021#106]
CSS and JavaScript file should be connected with the HTML to work the game properly. 
I would love to contribute and resolve this issue. Please assign this issue to me @deepakuniyaliit .

**Comment by HarshJ27** [comment]
Hi, @deepakuniyaliit I can easily resolve this issue. I am an aspiring web developer and I have my own portfolio website too.

**Comment by sujeetcodes** [comment]
hi there this is very easy task for me please assign it to me

**Comment by YuvrajSHAD** [comment]
is the issue resolved or still opened! i Like to give a try? 🙄

**Comment by sujeetcodes** [comment]
I think it's still open
