### ISSUE TITLE
Python Program- Design of Helical Spring

### ISSUE THREAD

**Issue by mugdhapendse** [deepakuniyaliit/hacktoberfest2021#62]
Through this code, anyone even with a non-technical background can get the design parameters of a Helical spring by giving inputs like length, modulus of rigidity, force applied.

It'd be great to get this assigned to me under the hacktoberfest2021 tag.

**Comment by k40t1k-sys** [comment]
Yes it sounds a great project but make sure to make it for the use of non-tech person.

**Comment by mugdhapendse** [comment]
Yes, I have made the PR.
