### ISSUE TITLE
Showing Excluded Project

### ISSUE THREAD

**Issue by sailesh307** [deepakuniyaliit/hacktoberfest2021#86]
why it is showing excluded project

![image](https://user-images.githubusercontent.com/39018215/135904558-b5aa3341-f18b-4dc3-8e34-8ec7a9f76275.png)

**Comment by deepakuniyaliit** [comment]
We are looking into it and trying to find out the reason behind exclusion. In case there is any update from your side, do comment here.

**Comment by sailesh307** [comment]
ok sir
