### ISSUE TITLE
To make UI more better

### ISSUE THREAD

**Issue by vishwas031** [deepakuniyaliit/hacktoberfest2021#93]
In MovieTime : https://github.com/deepakuniyaliit/hacktoberfest2021/tree/main/HTML%20CSS%20JavaScript/Movie-App_Nitin_Shaily
The Overview section can be made look good and the movies container can be aligned to center which would look good to users.

**Comment by vishwas031** [comment]
@deepakuniyaliit, @NitinShaily I would like to work on this issue.

**Comment by NitinShaily** [comment]
sure go for it
